### ISSUE TITLE
Remove duplicate milestone in roadmap section

### ISSUE THREAD

**Issue by cedricdiop** [reesykle/reesykle-website#38]
**Describe the bug**
In the Seedling stage of the roadmap, we are duplicating the `implement transactional` burns milestone. This milestone is no longer viable and we should completely remove it from the roadmap. 

**To Reproduce**
1. Go to 'https://reesykle.com/'
2. Click on 'Roadmap Section'
3. Scroll down to '.Seedling Stage'

**Expected behavior**
Remove the `implement transactional burn` milestone from the roadmap.

**Screenshots**
<img width="624" alt="Screen Shot 2022-02-13 at 7 30 32 PM" src="https://user-images.githubusercontent.com/95982162/153782473-a26bc6c2-f81e-42fd-b6b1-ef998fa88a69.png">

**Comment by Lauraine18** [comment]
I can take care of this
