### ISSUE TITLE
Remove Duplicate Menu Item

### ISSUE THREAD

**Issue by bryanherediax** [reesykle/reesykle-website#9]
# Overview
The menu bar has the `Ecosystem` menu item duplicated. 

<img width="1440" alt="Screen Shot 2021-11-18 at 1 50 46 PM" src="https://user-images.githubusercontent.com/59835769/142478429-dc6f2586-340d-4ada-91bc-7debaac96280.png">

**Comment by VedantPol** [comment]
hey, @bryanherediax I would like to work on this issue.

**Comment by VedantPol** [comment]
hey, @bryanherediax I could not replicate the issue.is the issue solved ?

**Comment by ZaidKhan144** [comment]
Yeah, It looks fixed to me too.

**Comment by bryanherediax** [comment]
@ZaidKhan144 @VedantPol Yeah, sorry, forgot to close this issue out.

**Comment by ZaidKhan144** [comment]
@bryanherediax no worries man and thanks you letting us know.
